replicaCount: 

resources:
  requests:
    cpu: 40m
    memory: 40M

ingress:
  hosts:
    - host: ${{values.app_name}}-dev.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ${{values.app_name}}-tls
      hosts:
        - ${{values.app_name}}-dev.azurelaboratory.com