apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: ${{values.app_name}} is a Python app that displays pod details and status
  annotations:
    github.com/project-slug: rodmhgl/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental