site_name: '${{values.app_name}}'
site_description: 'Comprehensive documentation for the ${{values.app_name}} service'
repo_url: https://github.com/azurelaboratory/${{values.app_name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - kroki

markdown_extensions:
  - markdown_inline_mermaid

nav:
  - Overview: 'index.md'
  - System Architecture: 'system-architecture.md'
  - Architecture: 'architecture.md'
  - Development Guide: 'development.md'
  - Operations Runbook: 'runbook.md'
  - Architectural Decisions:
    - 'ADR Index': 'adr/index.md'
    - 'ADR-001 Container Base Image': 'adr/adr-001-container-base-image.md'