site_name: '${{values.app_name}}'
site_description: 'Main documentation for the python-app'
repo_url: https://github.com/rodmhgl/${{values.app_name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting Started: 'docs/index.md'
